### ISSUE TITLE
Compact mode overlap with logo

### ISSUE THREAD

**Issue by InnilToo** [Xbozon/rpg-styled-ui#8] opened 2021-09-28 10:06 UTC
When the Compact mode is toggled on the left menu gets covered by the logo.
![image](https://user-images.githubusercontent.com/33260912/135066301-d64f161a-e0bc-4093-be66-c3f9af28d6c5.png)
It's the same whether the Standard logo is toggled on or off.
I tried to test if it could be a conflict with one of my 80 other modules and the problem persisted with all other modules turned off.

**Comment by Xbozon** [comment] 2021-09-28 10:08
@InnilToo 
The problem is understandable, I will fix it soon. Thanks for the report.

**Comment by franckflo** [comment] 2021-09-28 15:16
I confirm I am seeing that as well. 

In any case: great job on that beautiful theme!

**Comment by thedigitaldungeonmaster** [comment] 2021-09-28 18:10
Can confirm...same bug here.

**Comment by Xbozon** [comment] 2021-09-28 20:27
@InnilToo @thedigitaldungeonmaster @franckflo 

Fixed in v0.4.1. The logo is now correctly hidden in compact mode. If the problem still occurs, please report it here.

**Closed by Xbozon** 2021-09-28 20:27 UTC
Labels: bug
