### ISSUE TITLE
404 error on downloading texture.png

### ISSUE THREAD

**Issue by riccisi** [Xbozon/rpg-styled-ui#11] opened 2021-09-28 13:24 UTC
The texture.png file is requested in download with the name in uppercase (Texture.png), but the file name is lowercase:
This is a problem if Foundry is installed on a case-sensitive operating system:

<img width="2120" alt="CleanShot_2021-09-28_at_15 06 482x" src="https://user-images.githubusercontent.com/6490765/135095083-9e843dec-20b7-4d7e-84f4-013925eb2993.png">

**Comment by Xbozon** [comment] 2021-09-28 13:56
Will be fixed in v0.4.1 patch. Thanks for report.

**Comment by Xbozon** [comment] 2021-09-28 20:28
Fixed in v0.4.1. The problem is caused by unused js code. If the problem still occurs, please report it here.

**Closed by Xbozon** 2021-09-28 20:28 UTC
Labels: bug
